language: perl

perl:
    - "5.22-shrplib"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential
    - sudo apt-get install -y graphviz

script: "perl Build.PL && ./Build manifest && ./Build installdeps && ./Build && ./Build test"
